### ISSUE TITLE
centos-65 requires patch utility due to nokogiri, only build-essential ~> 2.0.4 installs patch

### ISSUE THREAD

**Issue by martinb3** [aetrion/chef-dnsimple#21]
Hello! It appears that the latest nokogiri expects a `patch` command to be available on CentOS 6.5. `build-essential` was fixed in version 2.0.4 to install the `patch` package. However, this cookbook (dnsimple) is still pinned to an older `build-essential` version. 

https://github.com/opscode-cookbooks/build-essential/commit/97335d8823d35cb3f1fd8c5b64dee6deb9819b4a

**Comment by martinisoft** [comment]
hi @martinb3 

This _should_ be resolved in master and the soon to be released 1.1.0 version. Can you let us know if this is resolved for you?

**Comment by martinisoft** [comment]
Hi @martinb3 the 1.1.0 version should have resolved this issue for you. Please re-open this issue if that is not the case and we'll look at getting it resolved.

**Comment by martinb3** [comment]
Thanks @martinisoft!! :+1: :+1: :+1:
