### ISSUE TITLE
Ubuntu 14.04 package requirement

### ISSUE THREAD

**Issue by billmoritz** [aetrion/chef-dnsimple#23]
Fog requires zlib1g-dev to be installed.

**Comment by martinisoft** [comment]
Hi @billmoritz 

Do you know which version of fog needs this or is it any version?

**Comment by billmoritz** [comment]
Unfortunately after the outage I had to switch from DNSimple.  I won't be able to test.  According to #24 you're moving away from fog so this issue should go away.
